import assert from "node:assert/strict";
import test from "node:test";

import * as combatRules from "../Modul/splittermond-smoother-fight/scripts/combat-rules.js";

test("the public combat-rules facade retains its named export contract", () => {
    assert.deepEqual(Object.keys(combatRules).sort(), [
        "COMBAT_TICK_ACTIONS",
        "DEFAULT_CHECK_CONFIG",
        "actionRequiresTarget",
        "activeDefenseChangesDifficulty",
        "actorLinkUuid",
        "attackControlSelection",
        "attackControlState",
        "attackOutcomeChanged",
        "attackReadiness",
        "bestActiveDefenseValue",
        "calculateActiveDefenseValue",
        "combatActionHighlightState",
        "combatMessageKind",
        "combatTickActionsFor",
        "findDefensiveFeatureValue",
        "fullyConsumedCost",
        "hasSplittermondCheckUpdate",
        "hasTokenPositionUpdate",
        "healthCostFeedbackKind",
        "healthCostTotal",
        "isCombatantVisibleToUser",
        "isDamageSelectionAction",
        "isDefenderMasteryName",
        "isOffensiveCombatMessage",
        "isPlayersTurn",
        "isRedundantDeletedTokenLink",
        "isTargetDependentDifficulty",
        "linkMatchesCombatant",
        "mayRollCombatFumble",
        "mayUseRemoteChatActions",
        "mayViewActorResources",
        "mayViewTargetDefenses",
        "mayViewTargetDifficulty",
        "mergeActiveDefenseCheck",
        "normalizeActorUserLinks",
        "normalizeAudioFeedbackProfile",
        "normalizeFavoriteSkillIds",
        "normalizeSearchText",
        "normalizeTargetReferences",
        "normalizeTargetSelection",
        "normalizeUserTokenLinks",
        "numberOr",
        "parseActiveDefenseDescription",
        "parseStatusEffectLabel",
        "recalculateAttackReport",
        "reorderFavoriteSkillIds",
        "replaceManagedUserTokenLinks",
        "requiresRollManagementPermission",
        "resolveCombatEventOpenIds",
        "selectPersonalCombatant",
        "tickAdvanceConfirmed",
        "toggleFavoriteSkillId",
        "tokenDocumentCenter",
        "totalDegreesOfSuccess",
        "uniqueTokensByReference",
        "visibleCanvasCenterY",
        "withTemporarySetValues",
    ]);
});
