/** Feature-owned ephemeral state. */
export const hudState = {
    hud: null,
    renderTimer: null,
    canvasFrame: null,
    canvasMovementComplete: false,
    canvasGeneration: 0,
    canvasSignature: null,
    canvasPendingContext: null,
    canvasPartsPending: false,
    canvasValues: new Map(),
    canvasMarkup: new WeakMap(),
    movementDistanceCache: new WeakMap(),
    actionTooltip: null,
    actionTooltipRequest: null,
    hiddenByShortcut: false,
    actionMenuExpansionRequest: null,
    personalCombatId: null,
    personalCombatantId: null,
};
